apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: hubble-drop-eventer
    app.kubernetes.io/name: hubble-drop-eventer
    app.kubernetes.io/version: v0.0.0
  name: hubble-drop-eventer
rules:
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]
