apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: hubble-drop-eventer
    app.kubernetes.io/name: hubble-drop-eventer
    app.kubernetes.io/version: v0.0.0
  name: hubble-drop-eventer
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: hubble-drop-eventer
      app.kubernetes.io/name: hubble-drop-eventer
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hubble-drop-eventer
        app.kubernetes.io/name: hubble-drop-eventer
    spec:
      containers:
      - command:
        - /app/hubble-drop-eventer
        - -server
        - hubble-relay.${NAMESPACE}.svc.cluster.local
        - -port
        - "80"
        image: docker.io/wobin/hubble-drop-eventer:dev
        imagePullPolicy: IfNotPresent
        name: hubble-drop-eventer
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      serviceAccount: hubble-drop-eventer
      serviceAccountName: hubble-drop-eventer
