apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: hubble-drop-eventer
    app.kubernetes.io/name: hubble-drop-eventer
    app.kubernetes.io/version: v0.0.0
  name: hubble-drop-eventer
  namespace: ${NAMESPACE}
